<a href="https://colab.research.google.com/github/curogihu/ASP.net_CSharp_FinalExam/blob/master/tutorial_pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.cuda.is_available()

True

In [0]:
from __future__ import print_function

In [0]:
a = torch.empty(5, 3)

In [5]:
print(a)

tensor([[1.9799e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [5.4166e-05, 2.7448e-06, 2.0892e+20],
        [2.1971e-04, 2.5642e-09, 6.4896e-10],
        [2.7029e-06, 2.6953e-09, 5.0948e-14]])


In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[1.9799e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [5.4166e-05, 2.7448e-06, 2.0892e+20],
        [2.1971e-04, 2.5642e-09, 6.4896e-10],
        [2.7029e-06, 2.6953e-09, 5.0948e-14]])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7255, 0.7820, 0.2910],
        [0.1146, 0.0559, 0.1173],
        [0.2939, 0.9812, 0.4848],
        [0.3485, 0.3134, 0.9732],
        [0.5738, 0.8370, 0.5175]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.4303,  0.7920, -0.3835],
        [-1.9120, -2.2330,  0.0465],
        [-0.1939, -0.9146,  0.0087],
        [ 0.4563,  2.0792, -1.9379],
        [ 1.1533, -0.6417,  0.2414]])


In [12]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1798,  1.2519, -0.3620],
        [-1.4213, -1.2953,  0.2348],
        [ 0.0964, -0.5359,  0.4929],
        [ 1.2569,  2.1622, -1.8637],
        [ 1.2763,  0.2331,  0.8330]])


In [14]:
print(torch.add(x, y))

tensor([[-0.1798,  1.2519, -0.3620],
        [-1.4213, -1.2953,  0.2348],
        [ 0.0964, -0.5359,  0.4929],
        [ 1.2569,  2.1622, -1.8637],
        [ 1.2763,  0.2331,  0.8330]])


In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1798,  1.2519, -0.3620],
        [-1.4213, -1.2953,  0.2348],
        [ 0.0964, -0.5359,  0.4929],
        [ 1.2569,  2.1622, -1.8637],
        [ 1.2763,  0.2331,  0.8330]])


In [16]:
y.add_(x)
print(y)

tensor([[-0.1798,  1.2519, -0.3620],
        [-1.4213, -1.2953,  0.2348],
        [ 0.0964, -0.5359,  0.4929],
        [ 1.2569,  2.1622, -1.8637],
        [ 1.2763,  0.2331,  0.8330]])


In [17]:
print(x[:, 1])

tensor([ 0.7920, -2.2330, -0.9146,  2.0792, -0.6417])


In [18]:
print(x)

tensor([[-0.4303,  0.7920, -0.3835],
        [-1.9120, -2.2330,  0.0465],
        [-0.1939, -0.9146,  0.0087],
        [ 0.4563,  2.0792, -1.9379],
        [ 1.1533, -0.6417,  0.2414]])


In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to('cpu', torch.double))

tensor([[ 1.5092,  0.1532,  0.4660, -0.1752],
        [ 1.0964,  1.6547,  1.4446,  1.2223],
        [ 0.5587,  1.8588, -0.8855,  0.7179],
        [ 0.8642, -0.0761,  1.2684,  0.6441]], device='cuda:0')
tensor([[ 1.5092,  0.1532,  0.4660, -0.1752],
        [ 1.0964,  1.6547,  1.4446,  1.2223],
        [ 0.5587,  1.8588, -0.8855,  0.7179],
        [ 0.8642, -0.0761,  1.2684,  0.6441]], dtype=torch.float64)


In [0]:
# autograd_tutorial

In [27]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [28]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [29]:
print(y.grad_fn)

In [30]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [31]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


In [32]:
print(x.grad)

None


In [33]:
x = torch.randn(3, requires_grad=True)
y = x * 2

while y.data.norm() < 1000:
  y = y * 2
  
print(y)

tensor([ -499.9774,  -629.8967, -1668.0026], grad_fn=<MulBackward0>)


In [34]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [35]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as f

In [38]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    self.fc1 = nn.Linear(16 * 6 * 6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)
    
  def forward(self, x):
    x = f.max_pool2d(f.relu(self.conv1(x)), (2, 2))
    x = f.max_pool2d(f.relu(self.conv2(x)), 2)
    
    x = x.view(-1, self.num_flat_features(x))
    
    x = f.relu(self.fc1(x))
    x = f.relu(self.fc2(x))
    x =self.fc3(x)
    
    return x
  
  def num_flat_features(self, x):
    size = x.size()[1:]
    num_features = 1
    
    for s in size:
      num_features *= s
      
    return num_features
  
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [39]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [40]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.0176, -0.0966,  0.1375,  0.0651,  0.0520, -0.0963, -0.0487,  0.1458,
          0.0317, -0.0572]], grad_fn=<AddmmBackward>)


In [43]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.2519, grad_fn=<MseLossBackward>)


In [45]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])

In [47]:
net.zero_grad()

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([-0.0097,  0.0091, -0.0049, -0.0159,  0.0041, -0.0014])


In [0]:
learning_rate = 0.01

for f in net.parameters():
  f.data.sub_(f.grad.data * learning_rate)

In [50]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)

optimizer.zero_grad()
output = net(input)

loss = criterion(output, target)
loss.backward()
optimizer.step()

AttributeError: ignored